///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CI
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CIRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("df0b96ea-30d3-4b03-8d49-f707739dc83d")]
    public partial class CIRepository : RepoGenBaseFolder
    {
        static CIRepository instance = new CIRepository();
        CIRepositoryFolders.KeyPromptFormAppFolder _keypromptform;
        CIRepositoryFolders.MainFormAppFolder _mainform;

        /// <summary>
        /// Gets the singleton class instance representing the CIRepository element repository.
        /// </summary>
        [RepositoryFolder("df0b96ea-30d3-4b03-8d49-f707739dc83d")]
        public static CIRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CIRepository() 
            : base("CIRepository", "/", null, 0, false, "df0b96ea-30d3-4b03-8d49-f707739dc83d", ".\\RepositoryImages\\CIRepositorydf0b96ea.rximgres")
        {
            _keypromptform = new CIRepositoryFolders.KeyPromptFormAppFolder(this);
            _mainform = new CIRepositoryFolders.MainFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("df0b96ea-30d3-4b03-8d49-f707739dc83d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The KeyPromptForm folder.
        /// </summary>
        [RepositoryFolder("ee08961b-b0d8-4c33-b2bb-d527967a7c79")]
        public virtual CIRepositoryFolders.KeyPromptFormAppFolder KeyPromptForm
        {
            get { return _keypromptform; }
        }

        /// <summary>
        /// The MainForm folder.
        /// </summary>
        [RepositoryFolder("c20612a9-3508-41fb-a088-eff2bb811e46")]
        public virtual CIRepositoryFolders.MainFormAppFolder MainForm
        {
            get { return _mainform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class CIRepositoryFolders
    {
        /// <summary>
        /// The KeyPromptFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("ee08961b-b0d8-4c33-b2bb-d527967a7c79")]
        public partial class KeyPromptFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _mbtnokInfo;

            /// <summary>
            /// Creates a new KeyPromptForm  folder.
            /// </summary>
            public KeyPromptFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("KeyPromptForm", "/form[@automationid='KeyPromptForm']", parentFolder, 30000, null, true, "ee08961b-b0d8-4c33-b2bb-d527967a7c79", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "?/?/text[@accessiblerole='Text']", "?/?/text[@accessiblerole='Text']", 30000, null, "550dd58e-ddcc-4f24-ad85-c4698ac71732");
                _mbtnokInfo = new RepoItemInfo(this, "MBtnOK", "button[@text='OK']", "button[@text='OK']", 30000, null, "e7c5d933-b053-40a0-963c-8a6e07f63e42");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ee08961b-b0d8-4c33-b2bb-d527967a7c79")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ee08961b-b0d8-4c33-b2bb-d527967a7c79")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("550dd58e-ddcc-4f24-ad85-c4698ac71732")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("550dd58e-ddcc-4f24-ad85-c4698ac71732")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The MBtnOK item.
            /// </summary>
            [RepositoryItem("e7c5d933-b053-40a0-963c-8a6e07f63e42")]
            public virtual Ranorex.Button MBtnOK
            {
                get
                {
                    return _mbtnokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The MBtnOK item info.
            /// </summary>
            [RepositoryItemInfo("e7c5d933-b053-40a0-963c-8a6e07f63e42")]
            public virtual RepoItemInfo MBtnOKInfo
            {
                get
                {
                    return _mbtnokInfo;
                }
            }
        }

        /// <summary>
        /// The MainFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("c20612a9-3508-41fb-a088-eff2bb811e46")]
        public partial class MainFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new MainForm  folder.
            /// </summary>
            public MainFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MainForm", "/form[@automationid='MainForm']", parentFolder, 30000, null, true, "c20612a9-3508-41fb-a088-eff2bb811e46", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", "?/?/button[@accessiblename='Close']", 30000, null, "4eec3dda-55f8-4544-a42c-87f956cfb2ab");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c20612a9-3508-41fb-a088-eff2bb811e46")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c20612a9-3508-41fb-a088-eff2bb811e46")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("4eec3dda-55f8-4544-a42c-87f956cfb2ab")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("4eec3dda-55f8-4544-a42c-87f956cfb2ab")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
